libraries/Bluefruit52Lib/keywords.txt
libraries/Bluefruit52Lib/src/BLECharacteristic.cpp
libraries/Bluefruit52Lib/src/BLECharacteristic.h
libraries/Bluefruit52Lib/src/services/BLEDfu.cpp

Change setWriteAuthorizeCallbak to setWriteAuthorizeCallback, assuming its a typo.

Fix setWriteAuthorizeCallback typo

---

libraries/Bluefruit52Lib/src/bluefruit.cpp
libraries/Bluefruit52Lib/src/bluefruit.h

(For consistency with every other BLE_GATT* #define)

BLEGATT_ATT_MTU_MAX should be BLE_GATT_ATT_MTU_MAX

---

libraries/Bluefruit52Lib/src/bluefruit.cpp

Fixed a typo from my previous PR; sorry about that.

Typo in _ppcp_conn_sup_timeout logging

---

libraries/FileSystem/src/InternalFS.cpp
libraries/FileSystem/src/InternalFS.h

Unmount the FS before formatting

---

cores/nRF5/WInterrupts.c

Fixes adafruit/Adafruit_nRF52_Arduino#259

Fix interrupts for device with multiple I/O Ports

---

libraries/Bluefruit52Lib/keywords.txt

Just a minor change in spelling error from `Serivce` to `Service`. Thank you 🙇‍♀

Fix Service spelling

---

cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_CDC.cpp
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/cdc/cdc.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/cdc/cdc_device.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/hid/hid.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/hid/hid_device.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/midi/midi.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/midi/midi_device.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/msc/msc.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/msc/msc_device.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/common/tusb_common.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/common/tusb_compiler.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/common/tusb_types.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/device/dcd.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/device/usbd.c
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/device/usbd.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/tusb_option.h
cores/nRF5/Adafruit_TinyUSB_Core/tusb_config.h
cores/nRF5/Arduino.h
cores/nRF5/compiler_macro.h
cores/nRF5/hooks.c
cores/nRF5/rtos.cpp
cores/nRF5/sysview/SEGGER_SYSVIEW_FreeRTOS.c
cores/nRF5/utility/debug.cpp
cores/nRF5/verify.h
libraries/Bluefruit52Lib/src/BLEAdvertising.cpp
libraries/Bluefruit52Lib/src/BLEDiscovery.cpp
libraries/Bluefruit52Lib/src/services/BLEHidGeneric.h
libraries/InternalFileSytem/src/flash/flash_cache.c
libraries/InternalFileSytem/src/flash/flash_nrf5x.c

Enhance Serial.available() and bool()

---

.travis.yml
cores/nRF5/WInterrupts.c
cores/nRF5/freertos/portable/CMSIS/nrf52/port_cmsis_systick.c
cores/nRF5/utility/AdaCallback.c
cores/nRF5/utility/AdaCallback.h
cores/nRF5/utility/debug.cpp
cores/nRF5/utility/utilities.c
cores/nRF5/wiring_analog_nRF52.c
libraries/Bluefruit52Lib/library.properties
libraries/Bluefruit52Lib/src/bluefruit.cpp
libraries/Bluefruit52Lib/src/clients/BLEClientHidAdafruit.cpp
libraries/Bluefruit52Lib/src/utility/bonding.cpp
libraries/RotaryEncoder/RotaryEncoder.cpp
libraries/RotaryEncoder/SwRotaryEncoder.cpp
platform.txt
tools/build_all.py

- Also refactor Adacallback
- clean up warnings

fix #240 let travis build all examples each commit 

---

changelog.md
cores/nRF5/Arduino.h
cores/nRF5/Tone.cpp
cores/nRF5/Tone.h

added Tone() 

---

README.md

Its Nordic chip instade of Noric

Fix typo for nordic in Readme.md

---

cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_CDC.cpp
cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_CDC.h
cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_Device.cpp
cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_Device.h

fix auto descriptor's auto interface e.g MIDI interface

---

cores/nRF5/utility/adafruit_fifo.cpp
cores/nRF5/utility/adafruit_fifo.h
libraries/Bluefruit52Lib/examples/Peripheral/image_upload/image_upload.ino
libraries/Bluefruit52Lib/examples/Peripheral/throughput/throughput.ino
libraries/PDM/src/PDM.h
tools/build_all.py

- able to draw 240x240 image
- improve mutex lock/unlock for fifo used by bleuart

enhance image_upload example

---

libraries/Bluefruit52Lib/src/services/BLEDis.cpp
libraries/Bluefruit52Lib/src/services/BLEDis.h

- inline function for no-length API
- clean up using strarr_len
- handle PNP_ID char
@elral

follow up to pr #336 , close #335

---

cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_Device.cpp
cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_Device.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/common/tusb_types.h
cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/device/usbd.h

- https://github.com/adafruit/ArduinoCore-samd/pull/179
- https://github.com/adafruit/ArduinoCore-samd/pull/173
- https://github.com/adafruit/ArduinoCore-samd/pull/172
- https://github.com/adafruit/ArduinoCore-samd/pull/170
- https://github.com/adafruit/ArduinoCore-samd/pull/169
- https://github.com/adafruit/ArduinoCore-samd/pull/168

sync with tinyusb core from samd with folowing PRs

---

tools/build_all.py

skip homekit example

---

libraries/Wire/Wire.h
libraries/Wire/Wire_nRF52.cpp
libraries/Wire/examples/master_scan/master_scan.ino
variants/circuitplayground_nrf52840/variant.h

`Wire1` for on-board lis3dh connection, `Wire` for external pad on cplay bluefruit

add second hardware i2c as Wire1 for cplayground bluefruit

---

libraries/Bluefruit52Lib/examples/Central/central_throughput/central_throughput.ino

Fix #378: [-Wunused-variable]

---

libraries/Bluefruit52Lib/examples/Central/central_ti_sensortag_optical/central_ti_sensortag_optical.ino

Fix #380 by removing the unused variable.

Fix #380 [-Wunused-variable]

---

libraries/Bluefruit52Lib/examples/Peripheral/blemidi/blemidi.ino

Fix #379 by using unsigned integers and adjusting the check for first index.

Fix #379 [-Wsign-compare]

---

libraries/SPI/SPI.cpp

which cause 1/2 screen drawing with mandelbrot example sketch

fix spim is limit up to 64KB each transfer

---

cores/nRF5/linker/nrf52832_s132_v6.ld

- from 0x3400 to 0x3600, fix #412

increase SD ram for nrf52832

---

libraries/Bluefruit52Lib/src/BLECharacteristic.cpp
libraries/Bluefruit52Lib/src/BLEConnection.cpp
libraries/Bluefruit52Lib/src/BLEConnection.h

Fix sporadic hangup when stopping notifies - Resolves #443

---

libraries/Bluefruit52Lib/examples/Peripheral/bluefruit_playground/bluefruit_playground.ino

Since there's no Button 2 or Buzzer, I just had it check if they existed so it can still work on future boards without being too specific.

Updated bluefruit_playground to compile on Bluefruit Feather Sense

---

.github/workflows/githubci.yml
cores/nRF5/main.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitAddressablePixel.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitAddressablePixel.h
libraries/BLEAdafruitService/src/services/BLEAdafruitColor.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitColor.h
libraries/BLEAdafruitService/src/services/BLEAdafruitGesture.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitGesture.h
libraries/BLEAdafruitService/src/services/BLEAdafruitProximity.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitProximity.h
libraries/BLEAdafruitService/src/services/BLEAdafruitQuaternion.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitQuaternion.h
libraries/BLEAdafruitService/src/services/BLEAdafruitSensor.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitSensor.h
libraries/BLEAdafruitService/src/services/BLEAdafruitSound.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitSound.h
libraries/Bluefruit52Lib/examples/Peripheral/bleuart/bleuart.ino
libraries/Bluefruit52Lib/examples/Peripheral/bluefruit_playground/bluefruit_playground.ino
libraries/Bluefruit52Lib/examples/Peripheral/neopixel/neopixel.ino
tools/build_all.py
variants/clue_nrf52840/variant.h
variants/feather_nrf52840_sense/variant.cpp
variants/feather_nrf52840_sense/variant.h

It turns out the PR add more services than just sound, the list is:
- Sound
- Color
- Proximity
- Gesture
Also other minor fix
- force while(!Serial) when debug level is enabled.
- fix feather sense D13 LED pin map

Add more sensor services

---

boards.txt
cores/nRF5/WInterrupts.c
cores/nRF5/freertos/config/FreeRTOSConfig.h
cores/nRF5/main.cpp
cores/nRF5/sysview/SEGGER_SYSVIEW_FreeRTOS.c
libraries/Wire/Wire_nRF52.cpp

Of course, this commit ensures the following:
* Zero change to BSP defaults
* Zero change to compiled code
* Zero change to UI / menu options

[WIP] Enable/Disable SysView via CFG_SYSVIEW

---

cores/nRF5/main.cpp
libraries/Bluefruit52Lib/examples/Peripheral/bleuart/bleuart.ino

fix #475 , per user feedback. Move the blocking to user sketch.

remove the force Serial connected when debug is eanbled.

---

changelog.md
libraries/Bluefruit52Lib/library.properties
platform.txt

increase version and update changelog

Update TinyUSB to commit c59fa77 due to a bug in the stack

---

cores/nRF5/WInterrupts.c

Fix  #477
Although the bug is confirmed (see [gist](https://gist.github.com/henrygab/d02e6b03be5636d51fc0fe8748cb3b21)), the fix is not fully ready.
Although the concept is clear from the first two commits in this branch, there is still at least one bug that prevents integration at the moment.
tagging myself @henrygab

GPIOTE fixes for attachInterrupt() / detachInterrupt()

---

cores/nRF5/freertos/portable/CMSIS/nrf52/port_cmsis_systick.c

Third time is the charm I hope.
I have no issue with git, just not familiar with GH workflows and your branch usage.
Now that we have clarified master is your main integration branch, I have moved those 3 commits over to my (up to date) master and made this PR out of that. Let's see if the commit validation is happier on master at last...

Power fixes

---

libraries/Bluefruit52Lib/src/BLECharacteristic.cpp

fix typo #569

---

cores/nRF5/sysview/Config/SEGGER_SYSVIEW_Config_FreeRTOS.c

which contain the endpoint race fix from upstream. fix #565

update tinyusb core to commit 2afb2320e03e26c765aaeb51d430325b8adcdbf9

---

cores/nRF5/TinyUSB/Adafruit_TinyUSB_nRF.cpp

- update tinyusb core to commit e7b892095f2bb5d8bef6a748238369bdd268ed5e
- Get String Descriptor support for interface
- Get line conding API for cdc
similar to https://github.com/adafruit/ArduinoCore-samd/pull/262

update tinyusb core

---

cores/nRF5/freertos/portable/CMSIS/nrf52/port_cmsis_systick.c
libraries/Bluefruit52Lib/examples/Peripheral/beacon/beacon.ino
libraries/Bluefruit52Lib/src/BLEPeriph.cpp
libraries/Bluefruit52Lib/src/BLESecurity.cpp
libraries/Bluefruit52Lib/src/utility/bonding.cpp

remove beacon blocking wait for Serial connection for #580

fix some warnings

---

cores/nRF5/Uart.cpp
cores/nRF5/Uart.h

The documentation states that mutexes must not be used within the ISR, so I fixed that.
https://www.freertos.org/a00124.html

fix to not use mutex in ISR

---

libraries/Bluefruit52Lib/src/BLEConnection.cpp
libraries/Bluefruit52Lib/src/BLEConnection.h
libraries/Bluefruit52Lib/src/BLEPeriph.cpp
libraries/Bluefruit52Lib/src/BLEPeriph.h

- Add some functions related to connection parameter
- Remove the process that conflicts with the BLEConnection::requestConnectionParameter() function

Fix connection parameter

---

libraries/Bluefruit52Lib/examples/Peripheral/arduino_science_journal/arduino_science_journal.ino
libraries/Bluefruit52Lib/examples/Peripheral/bluefruit_playground/bluefruit_playground.ino
libraries/Bluefruit52Lib/examples/Peripheral/nrf_blinky/nrf_blinky.ino
libraries/Bluefruit52Lib/src/BLECharacteristic.cpp
libraries/Bluefruit52Lib/src/BLECharacteristic.h
libraries/Bluefruit52Lib/src/bluefruit.cpp
variants/circuitplayground_nrf52840/variant.h
variants/clue_nrf52840/variant.h
variants/feather_nrf52840_express/variant.h
variants/feather_nrf52840_sense/variant.h
variants/metro_nrf52840_express/variant.h

- added firmware sketch to use with Arduino Science Journal app https://www.arduino.cc/education/science-journal
- tested on CLUE, Feather nRF52840 Sense and CPB with on-board sensor.
- Everything work well: accel, gyro, magnetic, temperature, pressure, humid, proximity, color, light, sound/noise PDM. But some may need a bit sensor data tune-up (and/or calibrate etc ..)
Update: have been following closely to [Nano33BLESenseFirmware](https://github.com/arduino-libraries/Arduino_ScienceJournal/blob/master/examples/Nano33BLESenseFirmware/Nano33BLESenseFirmware.ino#L19) and support all of those sensors. But I just realize there is also LED, Input, Output characteristic as well [PhysicsLabFirmware.ino](https://github.com/arduino-libraries/Arduino_ScienceJournal/blob/master/examples/PhysicsLabFi …

Science journal

---

.github/workflows/githubci.yml
libraries/Bluefruit52Lib/src/services/BLEHidGeneric.h

- Fix gamepad report type conflict
- Also clean up ci yml a bit

Fix gamepad report type conflict

---

cores/nRF5/HardwarePWM.cpp
cores/nRF5/Tone.cpp
cores/nRF5/WString.cpp
libraries/BLEAdafruitService/src/services/BLEAdafruitSensor.h
libraries/Bluefruit52Lib/examples/Central/central_pairing/central_pairing.ino
libraries/Bluefruit52Lib/examples/Peripheral/ancs_oled/ancs_oled.ino
libraries/Bluefruit52Lib/examples/Peripheral/arduino_science_journal/arduino_science_journal.ino
libraries/Bluefruit52Lib/examples/Peripheral/image_eink_transfer/image_eink_transfer.ino
libraries/Bluefruit52Lib/src/utility/bonding.cpp
libraries/SPI/SPI.cpp
libraries/SoftwareSerial/SoftwareSerial.h
tools/build_all.py

- update tinyusb and fix warnings

Fix warning

---

libraries/Bluefruit52Lib/examples/Peripheral/beacon/beacon.ino

fix #580 
- change default manuf to Nordic
- use same uuid, major, minor as nordic beacon example

update beacon example

---

libraries/PDM/examples/PDMSerialPlotter/PDMSerialPlotter.ino
libraries/PDM/src/PDM.cpp

fix PDM hfclk request when softdevice is enabled.

fix pdm issue when bluefruit is enabled

---

cores/nRF5/freertos/Source/portable/MemMang/heap_3.c
cores/nRF5/freertos/config/FreeRTOSConfig.h
cores/nRF5/new.cpp
cores/nRF5/rtos.h
keywords.txt
platform.txt

fix #35, use wrap linker option to implement thread-safe malloc/free

implemnent thread-safe malloc/free using --wrap linker option

---

.github/workflows/githubci.yml
cores/nRF5/common_func.h
cores/nRF5/wiring.c
tools/build_all.py

- fix reboot issue when occasionally when SD is busy https://forums.adafruit.com/viewtopic.php?p=965956#p965956
- also fix ci and 
- improve build time with python pool
- bump up submodule nRFCrypto and TinyUSB lib

Fix reboot issue
