adafruit/Adafruit_nRF52_Arduino

- cores/nRF5/Uart.cpp
- cores/nRF5/wiring_analog.h
- cores/nRF5/wiring_analog_nRF52.c
Implemented analog oversampling which allows any analog pin to be automatically sampled muliple times (upto 256) when analogRead() is used. An average of the samples is then returned. Useful to improve noise performance without extra code.
Implemented Uart::flush(). Was there a specific reason for not originally implementing this? Seems like a very useful addition.
> Added analog oversampling

- libraries/Bluefruit52Lib/src/services/BLEHidAdafruit.cpp
Japanese keyboard requires key code larger than 101
> enable BLEHidAdafruit to send key codes larger than 101.

- libraries/Bluefruit52Lib/src/services/BLEHidGeneric.cpp
Otherwise getting the following error:
uint16_t BLECharacteristic::write(const void*, uint16_t): 431: verify failed, error = NRF_ERROR_INVALID_ADDR
Signed-off-by: Robert Hodaszi <hodrob84@gmail.com>
> BLEHidGeneric: fix missing writeN() function update

- cores/nRF5/wiring_analog_nRF52.c
The analog gain is a bit confusing as the input range is calculated by dividing Vref by the gain not multiplying. Using VDD/4 as ref results in an input range of (VDD/4)/gain therefore if a range of 0...VDD is needed gain must be 1/4 not 4 (check p363 of product spec)
> Fixed using VDD as analog reference

- libraries/Bluefruit52Lib/src/services/BLEDfu.cpp
Looks like a small typo in BLEDfu. setTempMemory is being called on the packet characteristic again rather than the revision.
> Fix dfu temp memory typo

- libraries/Servo/src/Servo.h
- libraries/Servo/src/nrf52/Servo.cpp
- libraries/Servo/src/nrf52/ServoTimers.h
As notified there https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/68 :
Your implementation use hardcoded pulse limits and doesn't use user's values given to the attach function.
In addition, microseconds functions doesn't use ou return a µs value.
I had to modify the type of min and max parameters to allow storage of values up to 2500µs... maybe it had would be better to add new params (ex : minus and maxus) to avoid confusion with other ARCH...
> fix hardcoded pulse limits

- cores/nRF5/debug.cpp
Output of `dbgDumpMemory` is completely broken when buffer size is > 255 because the code to handle that case multiplies a char (instead of its int value) by 2. This fixes the problem.
Before the fix, the output of dumping a buffer between 2^8 and 2^16 bytes long looks like:
00:  255lX 255lX 255lX 255lX
because `‘2’ * 2` happens to be `‘d’` so the format string ends up being `“%0dlx”`. Beyond 2^16 bytes, it would fail even harder, as `‘d’ * 2` isn’t a valid format character. I didn’t try it. 
This is an untested code change; I am not set up to build the core and test it here, I just ran into this bug while debugging a library I am working on.
> Fixed output of dbgDumpMemory when buffer size > 255 bytes

- libraries/Bluefruit52Lib/src/bluefruit.cpp
- libraries/Bluefruit52Lib/src/bluefruit.h
Currently peripheral connection supevision timeout is hardcoded to 2000ms; it should be configurable.
> Add a way to set connection supervision timeout

- libraries/Bluefruit52Lib/src/bluefruit.cpp
This change fixes support for running with using the internal RC oscillator for the Low Frequency clock. This is helpful when using a generic nRF52 module.
> Added support for using the Low Frequency RC oscillator

- libraries/Bluefruit52Lib/src/BLECharacteristic.cpp
`read32()` does not work correctly when payload > 0x0000ffff.
Because `read32()` has incorrect cast to`uint16_t` inside the function...
> Bug Fix: Incorrect cast on BLECharacteristic::read32()

- cores/nRF5/utility/AdaCallback.h
- libraries/Bluefruit52Lib/src/bluefruit.cpp
(and some other CFG_ items that were in the same files)
This is because the default memory allocations are quite conservative assuming that folks will do lots of work in the callbacks etc (which is fairly good assumption). However this can lead to a lot of 'wasted' RAM. The `dbgMemInfo` tool (which is great BTW) can then be used to look at the memory usage and the values can be fine tuned (at least with PlatformIO).
> Allow the task stack sizes to be configured

- libraries/FileSystem/src/InternalFS.cpp
- libraries/FileSystem/src/InternalFS.h
Restructured so the class can be extended to add support for external flash chips. This would be used as follows:
ExtFlashFS.h
```C++
#ifndef EXT_FLASH_FS_MANAGER_H
#define EXT_FLASH_FS_MANAGER_H
// Internal Flash uses ARM Little FileSystem
// https://github.com/ARMmbed/littlefs
#include "InternalFS.h"
class ExtLittleFS : public LittleFS
{
protected:
virtual int _flash_read (lfs_block_t block, lfs_off_t off, void *buffer, lfs_size_t size);
virtual int _flash_prog (lfs_block_t block, lfs_off_t off, const void *buffer, lfs_size_t size);
virtual int _flash_erase (lfs_block_t block);
virtual void _flash_erase_all();
virtual int _flash_sync ();
public:
ExtLittleFS(void);
~ExtLittleFS();
bool begin(void);
};
extern ExtLittleFS ExtFlashFS;
#endif // !EXT_FLASH_FS_MANAGER_H
```
ExtFlashFS.cpp …
> LittleFS extension rework

- variants/feather_nrf52840_express/variant.cpp
- variants/feather_nrf52840_express/variant.h
This fixes the issues identified in #250.
* Update definition of `PINS_COUNT` and `NUM_DIGITAL_PINS` to reflect mappable pin count for this board (34).
* Update `g_ADigitalPinMap` to define only 34 pins.
* Add comments to `g_ADigitalPinMap`, describing the non-mapped 14 pins, and why they are not listed.
> Fix #250 -- wrong values for g_ADigitalPinMap

- libraries/Bluefruit52Lib/examples/Hardware/adc_vbat/adc_vbat.ino
The nrf52840 uses 150K + 150K as the VBATT voltage divider and connects to pin A6 rather than A7.
The cleanest way to support old and new boards is to use an ifdef and change mvToPercent to deal in real mV since full charge isn't 3V on the ADC pin for nrf52840.
I'm not fully satisfied with the new mvToPercent since it looks like the battery never quite reaches 4200 mV.
> Update adc_vbat.ino to also work with nrf52840

- cores/nRF5/utility/SoftwareTimer.h
The SoftwareTimer provided by the library is missing a function for resetting it.
Also, I want to reset this timer from an ISR attached by attachInterrupt. Based on the documentation at https://www.freertos.org/FreeRTOS-timers-xTimerResetFromISR.html, I figured it was necessary to use the ISR-safe functions, so there's ISR-safe equivalents included. I'm not quite certain about their name, though; I used ISR because that was what was in my head at the time but it might be more appropriate to name them more in line with Arduino-style "attachInterrupt" thus becoming "resetFromInterrupt" etc.
Finally, the timer I want must be non-repeating, only getting started when an interrupt tells it to start. So I added a begin()-function that adds a boolean to its signature to specify whether the timer …
> Extend SoftwareTimer with option to make it non-repeating, add reset function & ISR-safe functions.

- libraries/Bluefruit52Lib/src/bluefruit.cpp
- libraries/Bluefruit52Lib/src/bluefruit.h
Adding functions with corrected spelling:
setApperance -> setAppearance
getApperance -> setAppearance
Not removing incorrect spelling for backwards-compatibility
> Adding corrected spelling

- libraries/Bluefruit52Lib/examples/Peripheral/hid_camerashutter/hid_camerashutter.ino
Consumer usage codes are in Adafruit_nRF52_Arduino/cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/hid/hid.h (or at least that is where I found them) - not BLEHidGeneric.h
> Corrected location of consumer usage codes

- cores/nRF5/new.cpp
Without this change, you'll get link errors for a variety of destructors complaining about "undefined operator delete(void *, unsigned int)" when you try to compile with -std=gnu++14 (or gnu++17) with GCC 7.2.1 (arm-none-eabi-gcc 7-2017q4)
> Added a couple delete operators to make std=gnu++14/17 link

- cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_CDC.cpp
- cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/cdc/cdc_device.c
- cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/cdc/cdc_device.h
Fixes issue #307.
Make CDC serial functions that read a single character return an int rather than signed character so -1 for no data available can be distinguished from reading byte 0xFF.
> Make Serial::read and dependant functions 8-bit clean.

- cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_CDC.cpp
- cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_CDC.h
- cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/cdc/cdc_device.c
- cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/cdc/cdc_device.h
Add availableForWrite method to Serial
Compatible with the standard Arduino API. This will apply cleanly on top of the fix_serial patch.
> Add availableForWrite method to Serial.

- .travis.yml
- cores/nRF5/Adafruit_TinyUSB_Core/Adafruit_USBD_CDC.cpp
- libraries/Bluefruit52Lib/examples/Central/central_bleuart/central_bleuart.ino
- libraries/Bluefruit52Lib/examples/Central/central_custom_hrm/central_custom_hrm.ino
- libraries/Bluefruit52Lib/examples/Central/central_hid/central_hid.ino
- libraries/Bluefruit52Lib/examples/Central/central_throughput/central_throughput.ino
- libraries/Bluefruit52Lib/examples/Central/central_ti_sensortag_optical/central_ti_sensortag_optical.ino
- libraries/Bluefruit52Lib/examples/Peripheral/ancs/ancs.ino
- libraries/Bluefruit52Lib/examples/Peripheral/bleuart/bleuart.ino
- libraries/Bluefruit52Lib/examples/Peripheral/bleuart_multi/bleuart_multi.ino
- libraries/Bluefruit52Lib/examples/Peripheral/client_cts/client_cts.ino
- libraries/Bluefruit52Lib/examples/Peripheral/custom_hrm/custom_hrm.ino
- libraries/Bluefruit52Lib/examples/Peripheral/custom_htm/custom_htm.ino
- libraries/Bluefruit52Lib/examples/Peripheral/image_upload/image_upload.ino
- libraries/Bluefruit52Lib/examples/Peripheral/rssi_callback/rssi_callback.ino
- libraries/Bluefruit52Lib/examples/Peripheral/rssi_poll/rssi_poll.ino
- libraries/Bluefruit52Lib/examples/Peripheral/throughput/throughput.ino
- libraries/Bluefruit52Lib/src/BLEAdvertising.cpp
- libraries/Bluefruit52Lib/src/BLEConnection.cpp
- libraries/Bluefruit52Lib/src/BLEConnection.h
- libraries/Bluefruit52Lib/src/BLEGatt.cpp
- libraries/Bluefruit52Lib/src/BLEPeriph.cpp
- libraries/Bluefruit52Lib/src/bluefruit.cpp
- libraries/Bluefruit52Lib/src/services/BLEUart.cpp
- libraries/Bluefruit52Lib/src/services/BLEUart.h
- tools/build_all.py
- add requestPHY() to switch to 2MB PHY, fix #83  #80
- add requestDataLengthUpdate() to increase data length
- add requestMtuExchange() to actively exchange MTU, fix #106
update throughput example, and added central_throughput example
> Maximize throughput

- cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/device/usbd.h
- cores/nRF5/utility/debug.cpp
Two types of warnings fixed.
warning: format '%X' expects argument of type 'unsigned int', but argument 3 has type 'int32_t {aka long int}' [-Wformat=]
The C++ specification requires "%X" to receive an unsigned value. Any other type (including signed values) is "undefined behavior".
warning: narrowing conversion of '(((int)itfnum) + 1)' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
Affected macros were returning a list of uint8_t values, used to define statically-allocated byte arrays.  Fixed by explicitly casting to `uint8_t` when doing arithmetic on any parameter.  Notation also added to call out implied range constraint on the parameter _itfnum.
> Fix multiple warnings when building.

- libraries/Bluefruit52Lib/src/services/BLEDis.cpp
- libraries/Bluefruit52Lib/src/services/BLEDis.h
Added some methods for setting more device informations.
See also Issue #335
> Additional Device Informations for ble

- cores/nRF5/common_func.h
- cores/nRF5/verify.h
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.h
- libraries/Bluefruit52Lib/src/BLEDiscovery.cpp
- libraries/Bluefruit52Lib/src/BLEGatt.cpp
- libraries/Bluefruit52Lib/src/bluefruit.cpp
- libraries/Bluefruit52Lib/src/services/BLEMidi.cpp
- libraries/Bluefruit52Lib/src/utility/bonding.cpp
- libraries/InternalFileSytem/src/flash/flash_cache.c
This PR allows v0.14.0 to compile cleanly (no warnings), allowing end-users to focus on issues within their own code.
* Fixes #344 - Use of uninitialized variable in Bluefruit library
* Fixes #345 - InternalFileSystem compiler warnings for comparing signed vs. unsigned
* Fixes #346 - Additional Bluefruit library compiler warnings
Note: I am not sure how to fully test these.  I ran the bleuart example, and verified UART capability. 
Of particular note is the changes to the InternalFileSystem library's flash_cache.c, function flash_cache_read().  Significant comments were added to help understand the implicit guarantees provided by the various code paths.  A PowerShell function mirroring the original code flow was written to generate results from various parameters.  A second PowerShell …
> Compile without warnings

- libraries/SPI/SPI.cpp
as 840 specs spim3 highspeed may need high drive
> use high drive H0H1 for SCK and MOSI for better performance at highseed 32Mhz

- cores/nRF5/WInterrupts.c
This only affects debug level 3 (Segger SysView) builds.
This allows SysView to properly represent time spent in ISRs attached using `AttachInterrupt()`.
> Record ISR entry/exit for `AttachInterrupt()`

- .travis.yml
- tools/build_all.py
Fixes #371
TravisCI imposes a per-job time limit.  This limit is fixed and non-configurable for free accounts as **`50`** minutes.  This limit is configurable but cannot exceed **`120`** minutes for enterprise / paid accounts.
The builds are currently taking approximately 75 minutes, building all samples for three distinct boards (variants) in a single job.  Because 75 minutes is greater than 50 minutes, this prevents users with only a free account from validating their changes using TravisCI prior to submitting their pull requests.
This change also dramatically reduces the (wall-clock) time for validation of a successful build (from ~75 minutes down to ~30 minutes).
> Split TravisCI build into one job per variant

- libraries/Bluefruit52Lib/examples/Projects/rssi_proximity/rssi_proximity_central/rssi_proximity_central.ino
Fix #382
Use uint32_t to store timestamp instead of int32_t.
Adjust comparison to use timestamp as a zero-basis.
> Fix #382: [-Wsign-compare]

- .travis.yml
- tools/build_all.py
This includes a few improvements.  Summarized:
* Disable lots of noisy output from build logs caused by Arduino mDNS
* Enable an environment variable to request a build with additional warnings enabled
Details follow, with line numbers referring to new line numbers.
In file `.travis.yml`:
1. lines 12-29: friendly names given to each job
2. lines 12-29: add second build per board that enables additional warnings (as Arduino user might)
3. lines 30-33: list jobs with additional warnings as 'allow_failures'; these jobs can fail without causing the build as a whole to fail, allowing addressing of warnings over time
4. lines 56-66L: enable firewall rules to remove all the **_really_** noisy output from Arduino's mDNS code, just before build starts
In file `tools/build_all.py`:
1. lines 11-17: …
> Improve Travis Builds (inc. additional warnings)

- cores/nRF5/Adafruit_TinyUSB_Core/tinyusb/src/class/hid/hid.h
minor typo in `tinyusb/src/class/hid/hid.h`
> [tusb]fix typo in comment

- .gitignore
- cores/nRF5/rtos.cpp
- cores/nRF5/rtos.h
- cores/nRF5/utility/AdaCallback.c
- cores/nRF5/verify.h
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.h
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h
- libraries/InternalFileSytem/examples/Internal_StressTest/Internal_StressTest.ino
Fix #350
Fix #325
Fix #227
Fix #222
Fix #393
@hathach -- This PR supercedes #372 (Guard against race conditions in Flash FS cache), as #72 was not really providing a proper fix of the underlying problem:
LFS itself is [not safe](https://github.com/ARMmbed/littlefs/issues/352) to call simultaneously from multiple contexts.
This PR solves this by wrapping the InternalFS API with a non-recursive mutex, as recommended.
I realize the PR uses newly declared wrapper functions.  I tried to avoid this, but the changes got messy quite quickly, mostly due to some of the macros used to verify return codes exiting the function (which would leak the mutex).  This is a reasonably clean solution, without the more drastic move to use of RAII objects such as …
> Serialize lfs

- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.h
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h
follow up to  #397, move lockFS/unlockFS to FileSystem class since it make more sense, and replace the native freeRTOS call with mutex (maybe helpful to port to other platform later on). Skip mutex for non-LFS function such as isDirectory(), isOpen(), name()
@henrygab for review
> Lfs followup

- cores/nRF5/utility/SoftwareTimer.cpp
> Remove unused variable.

- libraries/PDM/examples/PDMSerialPlotter/PDMSerialPlotter.ino
- libraries/PDM/src/PDM.cpp
- libraries/PDM/src/PDM.h
- variants/circuitplayground_nrf52840/variant.h
- also add define for PIN_PDM_DIN, PIN_PDM_CLK, PIN_PDM_PWR
- add PDM setPins() for custom board
> fix pdm issue with #352

- boards.txt
- variants/MDBT50Q_RX/variant.cpp
- variants/MDBT50Q_RX/variant.h
Add support for Raytac MDBT50Q - RX USB dongle based on nrf52840.
> Raytac mdbt50 q rx

- libraries/Bluefruit52Lib/examples/Peripheral/nrf_blinky/nrf_blinky.ino
- variants/feather_nrf52840_express/variant.h
- variants/metro_nrf52840_express/variant.h
- variants/pca10056/variant.h
- variants/raytac_mdbt50q_rx/variant.h
- simple LED + Button example using "nRF Blinky" mobile application. close #59 
- Also add PIN_BUTTON for variants
> add Nordic LED Button example

- cores/nRF5/utility/utilities.c
Recently modified device ID expression ("%08lX%08lX" -> "%08lu%08lu") incurs system hanging in release build and reset in debug build.
Revert to hex expression solves the problem.
> Fix wrong expression of device ID in getMcuUniqueID()

- cores/nRF5/Uart.cpp
The nRF52840 provides a second Serial interface, which now enables connecting sensors with RX/TX via Serial1 (at A0/A1). 
But the current implementation of Uart::begin(baud, config) does ignore the second configuration paramenter and sets allways SERIAL_8N1. 
This pull request does a first start and can also configure SERIAL_8E1, with EVEN parity. e.g.:  `Serial1.begin(9600, SERIAL_8E1);`
> Uart: support even parity SERIAL_8E1

- boards.txt
- variants/circuitplayground_nrf52840/variant.h
- variants/clue_nrf52840/variant.h
- variants/feather_nrf52840_express/variant.h
- variants/feather_nrf52840_sense/variant.h
- variants/itsybitsy_nrf52840_express/variant.h
- variants/metro_nrf52840_express/variant.h
- variants/particle_xenon/variant.h
- variants/pca10056/variant.h
Will help for boards that dont have SPI or have both SPI and QSPI
> add QSPI define for external flash

- variants/particle_xenon/variant.cpp
- variants/particle_xenon/variant.h
Removed duplicate pin mapping for the PRIMARY LED. Moved up all other pin mappings to account for the removed one.
> Xenon Support: Removed LED pin 22

- libraries/SPI/SPI.cpp
- variants/clue_nrf52840/variant.h
> add macro SPI_32MHZ_INTERFACE to variant to select SPI or SPI1 to use 32mhz SPIM3

- .gitignore
- cores/nRF5/Uart.cpp
- cores/nRF5/freertos/Source/include/FreeRTOS.h
- cores/nRF5/freertos/Source/include/task.h
- cores/nRF5/freertos/Source/tasks.c
- cores/nRF5/freertos/portable/CMSIS/nrf52/port_cmsis_systick.c
- cores/nRF5/freertos/portable/CMSIS/nrf52/portmacro_cmsis.h
- cores/nRF5/sysview/Config/Global.h
- cores/nRF5/sysview/Config/SEGGER_RTT_Conf.h
- cores/nRF5/sysview/Config/SEGGER_SYSVIEW_Conf.h
- cores/nRF5/sysview/Config/SEGGER_SYSVIEW_Config_FreeRTOS.c
- cores/nRF5/sysview/SEGGER/SEGGER.h
- cores/nRF5/sysview/SEGGER/SEGGER_RTT.c
- cores/nRF5/sysview/SEGGER/SEGGER_RTT.h
- cores/nRF5/sysview/SEGGER/SEGGER_RTT_ASM_ARMv7M.S
- cores/nRF5/sysview/SEGGER/SEGGER_RTT_printf.c
- cores/nRF5/sysview/SEGGER/SEGGER_SYSVIEW.c
- cores/nRF5/sysview/SEGGER/SEGGER_SYSVIEW.h
- cores/nRF5/sysview/SEGGER/SEGGER_SYSVIEW_ConfDefaults.h
- cores/nRF5/sysview/SEGGER/SEGGER_SYSVIEW_Int.h
- cores/nRF5/sysview/SEGGER_SYSVIEW_FreeRTOS.c
- cores/nRF5/sysview/SEGGER_SYSVIEW_FreeRTOS.h
@hathach -- This is a precursor to any further work on #431.  It focuses on updating the Segger SystemView / RTT files, without changing their use.  Two minor bug fixes also included.
1. [Adds](https://github.com/adafruit/Adafruit_nRF52_Arduino/commit/bc94b4872aee138da9f3796d98e0aa65ba053034) `/boards.local.txt` and `/platform.local.txt` to .gitignore, to prevent accidental pushes of those files.
2. [Copies](https://github.com/adafruit/Adafruit_nRF52_Arduino/commit/84b65a88c07123ea3144e42173fbcb20defc7356) SystemView 3.10 files over the existing versions, including adding two new files `SEGGER_RTT_printf.c` and `SEGGER_RTT_ASM_ARMv7M.S`.  
Note: Compilation at this commit fails with a linker error, `undefined reference to SEGGER_RTT_ASM_WriteSkipNoLock`.
3. …
> Update Segger SysView files to v3.10

- cores/nRF5/common_inc.h
- libraries/Adafruit_LittleFS/src/littlefs/lfs_util.h
Follow up to #454 https://github.com/adafruit/Adafruit_nRF52_Arduino/pull/454/files#r395434902
cause compilation error with debug level 1.
> partial revert PRITNF in lfs_util.h due to compilation error

- platform.txt
Macro expansion ARDUINO_BSP_VERSION from platform.txt
> Macro expansion ARDUINO_BSP_VERSION from platform.txt

- boards.txt
Fixes 473.  Updates the maximum data size for remaining nRF52840 boards that did not previously get the update.
Commit 583ad02a modified the linker script for the nRF52840, and the corresponding maximum data size was updated (decreased) due to increased RAM set aside for the SD device.
> Update all nRF52840 boards to match linker

- variants/particle_xenon/variant.cpp
- variants/particle_xenon/variant.h
Xenon board can tell when it is getting powered through the USB rather than a battery and when a battery is being charged. Added required pins inside variant files and the pins work as specified:
- When PIN_PWD is HIGH, Xenon is being powered through the USB
- When PIN_CHG is LOW, a battery attached to Xenon is being charged
Note: Prior to using these pins it is neccessary to specify pinMode(PIN_CHG, INPUT) and pinMode(PIN_PWR, INPUT) due to how they're being implemented in hardware. Using these two pins 3 states of power can be deduced:
- hasUsbPower = digitalRead(PIN_PWR);
- isCharging = (hasUsbPower && !digitalRead(PIN_CHG));
- onBatteryPower = !hasUsbPower;
BUTTON_FRESET pin number assignment was fixed as previously it was pointing to a wrong pin.
Added the missing LED1 …
> Added Missing Pin Assignments for Xenon Board

- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.h
Adds a truncate method with semantics like Unix ftruncate and a version with no parameter that truncates to the current file
position.
> Add truncate method to Adafruit_LittleFS_File.

- cores/nRF5/common_func.h
Fix #498 ... add type-safety for **_both_** C and C++
> type-safe array macros

- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.h
Just adding a missing file rename method in the LittleFS class.  Original code copied from ::remove and just changed to call lfs_rename.  Tested on a nRF52840-DK.
> Add a rename(oldfilename, newfilename) method to LittleFS class

- variants/pca10056/variant.h
Add the 2 missing LED defines. Tested on my board and LEDs 3 and 4 toggle as expected with this change.
> Add missing LED pin defines for PCA10056

- libraries/Bluefruit52Lib/src/BLEDiscovery.cpp
Recover gracefully when a BLE peripheral returns more than 4 characteristics in a reply to a discovery request by clamping the reply's characteristic count to match what's actually in the truncated reply.
Should fix issue #514.
> Fix  BLEDiscovery::discoverCharacteristic when the central device returns more than 4 Characteristics in a discovery request

- variants/pca10056/variant.cpp
Need to init the 2 missing onboard LEDs for pca10056.
Sorry! Would have added this in my previous PR but just noticed it!
> Init all onboard LEDs for pca10056

- cores/nRF5/TinyUSB/Adafruit_TinyUSB_nRF.cpp
latest freeRTOS change make usb much faster --> missing control status with touch 1200
> a few delay before enter dfu by touch1200

- cores/nRF5/TinyUSB/Adafruit_TinyUSB_nRF.cpp
- cores/nRF5/TinyUSB/tusb_config.h
- cores/nRF5/freertos/config/FreeRTOSConfig.h
- cores/nRF5/main.cpp
- libraries/Bluefruit52Lib/src/bluefruit.cpp
- fix POWER USB Ready may not  be handled when Bluefruit.begin() is invoked fast enough.
- fix #544 
- need https://github.com/hathach/tinyusb/pull/478 to be merged first then bump up the tinyusb core.
- Also clean up stuffs as well.
> fix power usbready not handled if bluefruit begin() is called fast enough

- libraries/Wire/Wire.h
- libraries/Wire/Wire_nRF52.cpp
To configure the I2C pins call Wire.setPins(SDA_Pin, SCL_pin) prior to Wire.begin()
> Added I2C pin configuration

- cores/nRF5/Arduino.h
- cores/nRF5/main.cpp
Without `resumeLoop`/`resumeLoopFromISR` functions, suspendLoop is the same as terminateLoop. This enables an interrupt to trigger looping (using `resumeLoopFromISR`), which can then operate for some time, then suspend itself.
Example use: Use an interrupt to detect when a switch in a key matrix is pressed. Debouncing with only interrupts is nearly impossible. This allows the interrupt to trigger a normal "keymatrix scan & debounce" loop, which runs normally until debouncing time is over, then the loop can be suspended (thereby saving tremendous amounts of power).
> Add resumeLoop functionality

- cores/nRF5/delay.c
- cores/nRF5/delay.h
- cores/nRF5/freertos/portable/CMSIS/nrf52/port_cmsis_systick.c
DWT must be previously enabled by user sketch with dwt_enable(). This should fix #451
> micro() use DWT cyclecount if enabled else use rtos tick

- cores/nRF5/Tone.cpp
> Minor cleanup

- cores/nRF5/RingBuffer.h
Currently, SERIAL_BUFFER_SIZE in cores/nRF5/RingBuffer.h is defined to have a specific value (64 in this case) regardless of whether it is already defined or not. This means that there is no way to change the size of the UART buffers without editing this file manually by each person who wants a different value. With the proposed change, the definition can be passed to the compiler from the command line and the header will honor it.
The equivalent header for the SAMD core (https://github.com/adafruit/ArduinoCore-samd/blob/bdf5ac811733a9fdaf618fc61d8f5dcb8303ca00/cores/arduino/RingBuffer.h#L31-L33) already allows this, so I don't think this is likely to cause any major problems.
> Make definition of SERIAL_BUFFER_SIZE check if it is already defined (allows easier UART buffer size adjustment)

- libraries/RotaryEncoder/library.properties
arduino-cli does a better job to catch library includes. This fixed current ci build
> fix ci build due to RotaryEncoder include

- cores/nRF5/TinyUSB/tusb_config.h
Same ideas as in commit f3a70865d42e7a9a1afdc81f25d2a2939a99f57b (PR #575 ), but for the equivalent definitions for the RX and TX buffers for the USB serial in cores/nRF5/TinyUSB/tusb_config.h.
This lets one use pass the preprocessor definitions CFG_TUD_VENDOR_RX_BUFSIZE and CFG_TUD_VENDOR_TX_BUFSIZE and not have the header override the desired values.
> Make definitions for TinyUSB serial TX/RX buffer sizes check if they are already defined (allows easier serial buffer size adjustment)

- .github/workflows/githubci.yml
replacing the add-path from github actions script so that CI keeps working...
message from github actions:
The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> replace add-path with GITHUB_PATH env variable

- libraries/Bluefruit52Lib/src/bluefruit.h
Hi, here comes a bugfix for a missing dereference. Combined with the headache of migration to PlatformIO Core 5.x, this caused me several hours frustration.. 
Probably I made the original erroneous pull-request into 0.21.0 from the beginning....
> Event dispatch bugfix

- cores/nRF5/itoa.c
- cores/nRF5/itoa.h
This change copies over itoa.h and itoa.c from https://github.com/adafruit/ArduinoCore-samd/tree/master/cores/arduino
This adds in the missing utoa and itoa functions when compiling using -std=c++17. This nRF52 core is currently using -std=gnu++11 in platform.txt so this isn't normally an issue.
Tested compiling a few example sketches successfully in the Arduino IDE with this change. Not tested on device, haven't ordered hardware yet.
I'm hoping to get this fixed to add support for building pigweed on top
of this core. See https://pigweed.dev/targets/arduino/target_docs.html if interested! :smile:
> Update itoa.c for -std=c++17 compatibility

- libraries/Bluefruit52Lib/src/services/BLEBeacon.cpp
The Endian-swap was missing on the BLEBeacon::setMajorMinor function. I was considering moving it into the start function, but as it was originally implemented in the constructor, I decided to add it to setMajorMinor instead.
> Endian-swap implemented in setMajorMinor

- libraries/Bluefruit52Lib/src/services/BLEMidi.cpp
- libraries/Bluefruit52Lib/src/services/BLEMidi.h
Fixes #528 
Warning: I am well outside my wheelhouse here ⚠️ 
I do not know  `beginTransmission()` and `endTransmission()` methods are for. I see that the MIDI Library's serialMIDI implementation ignores them (https://github.com/FortySevenEffects/arduino_midi_library/blob/d9149d19df867abbf78cfcd37ef9d0e14dedca7f/src/serialMIDI.h#L66), so I tried that here, and it worked! (As far as I can tell). Constructive criticism welcome.
> Adds MIDI Library v5 support

- .github/workflows/githubci.yml
- libraries/Bluefruit52Lib/src/services/BLEMidi.cpp
- libraries/Bluefruit52Lib/src/services/BLEMidi.h
- remove the include MIDI.h to prevent build error without MIDI Library installed
- update ci to use MIDI v5
> follow up to PR-609

- libraries/Bluefruit52Lib/examples/Peripheral/adv_AdafruitColor/adv_AdafruitColor.ino
CircuitPython has a whole structure around communicating data with advertisements that's very easy to use. I personally needed to move my peripheral device firmware to Arduino, but wasn't sure exactly how to format arbitrary data into an advertisement in such a format that it would be compatible with CircuitPython `Advertisement` subclasses. 
This sketch demonstrates the Bluefruit.Advertising API(). When powered up, the Bluefruit module will start advertising a packet compatible with the AdafruitColor class from CircuitPython (https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/master/adafruit_ble/advertising/adafruit.py)
In other words, `ble.start_scan(AdafruitColor)` in CircuitPython will hear an advertisement from this device containing the color 0x0F0033 (violet).
Presumably, …
> Add CircuitPython BLE AdafruitColor example

- cores/nRF5/linker/nrf52_common.ld
This update to the "nrf52_common.ld" linker script fixes the linker warning **warning: changing start of section .bss by 4 bytes** which is given to sketches that contain lots of static/global data.
> updated linker script to fix recurring issue with .bss linker warning

- cores/nRF5/freertos/portable/CMSIS/nrf52/port_cmsis_systick.c
- cores/nRF5/wiring.c
- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS.cpp
- libraries/Bluefruit52Lib/examples/Peripheral/pairing_passkey_arcada/pairing_passkey_arcada.ino
- libraries/Bluefruit52Lib/src/bluefruit.cpp
- libraries/Bluefruit52Lib/src/bluefruit.h
- libraries/Bluefruit52Lib/src/services/BLEHidAdafruit.cpp
- libraries/Bluefruit52Lib/src/services/BLEHidAdafruit.h
- libraries/Bluefruit52Lib/src/services/BLEHidGeneric.h
- libraries/PDM/src/PDM.cpp
- libraries/RotaryEncoder/RotaryEncoder.cpp
- libraries/SPI/SPI.cpp
- libraries/SPI/SPI.h
- libraries/SPI/SPI_nrf52832.cpp
- libraries/Servo/src/nrf52/Servo.cpp
- libraries/SoftwareSerial/SoftwareSerial.cpp
- libraries/Wire/Wire.h
- libraries/Wire/Wire_nRF52.cpp
- variants/feather_nrf52840_express/variant.h
- fix #600 , CRYPTOCELL_IRQn must be manually cleared even though we use no-interrupt version of libcrypto_cell. Otherwise this irq flag will prevent cpu to enter low power mode hence consume more power.
- Also separate pairing_passkey (using Serial) and pair_passkey_arcada that use TFT to display passkey.
> Fix cryptocell high power

- cores/nRF5/HardwarePWM.h
This simple fix is to resolve the issue with compilation errors on "atomic_uint32_t".  This is an alias for std::atomic<std::uint32_t>.  When replacing it with the unaliased type, the errors are gone.
> Fix to atomic compiler errors

- cores/nRF5/Uart.cpp
Hey,
Just a small addition: 31250 and 56000 baud are also supported.
Thanks,
Ciarán :)
> Add missing UART baud rates

- libraries/Bluefruit52Lib/src/BLECharacteristic.cpp
- libraries/Bluefruit52Lib/src/BLESecurity.cpp
- libraries/Bluefruit52Lib/src/bluefruit.cpp
Fix issue when bonding with peer device using public address where the IRK+address are not exchanged when pairing (since device think it is not necessary). Should fix #670
> fix bonding with public/static address

- cores/nRF5/common_func.h
When a library includes something that includes common_func.h from inside an extern "C" {} block, compilation will fail. This is at least an infelicity. This PR forces C++ linking in the C++ only parts of common_func.h allowing it to compile without mysterious failures.
> Allow common_func.h to compile without error when it is included inside extern "C"

- cores/nRF5/wiring.c
- cores/nRF5/wiring.h
- cores/nRF5/wiring_analog.h
- cores/nRF5/wiring_analog_nRF52.c
These additions
- add SAADC offset calibration to the analog library. Nordic recommends calibration if the system temperature is expected to change by more than 10 degrees C.
- add the ability to read the CPU (chip) temperature.
Notes:
- readCPUTemperature() returns a floating point value. Internally, the TEMP peripheral provides an integer with 1 LSB = 0.25 degrees C. Repeatability is +/- 0.25 C but accuracy is only +/- 5 C.  The floating point value is a convenience for the novice user. If just passing along the integer is preferred, I can change it.
- Though initiating offset calibration is probably the main reason for checking the temperature, readCPUTemperature() was added to wiring.c/h rather than to wiring_analog_. I'd be happy to move it if another location is preferred. I didn't …
> Add SAADC offset calibration and reading of CPU temperature

- cores/nRF5/Uart.cpp
Wait for TXSTOPPED event and for RXTO event. This is required before disabling UART to fully power down transceiver PHY. Otherwise transceiver will continue to consume ~900uA. 
fix #631
> Fix uarte not power down correctly

- boards.txt
- cores/nRF5/common_func.h
- cores/nRF5/main.cpp
- platform.txt
- tools/makeboards.py
- Add debug output menu to select log output channel to Serial (CDC), Seria1 (HWUART) or or Segger RTT
- fix #416
> add menu debug out option to select output meessage channel

- libraries/Wire/Wire_nRF52.cpp
clear STOPPED event when start transmission,  which could be caused by… missing ack from previous transaction. Part of effort to resolve
- https://github.com/adafruit/Adafruit_LTR390/issues/2
> clear STOPPED event when start transmission,

- cores/nRF5/freertos/Source/include/projdefs.h
Use uint64_t for intermediate calculate of pdMS_TO_TICKS so stop integer overflow for long ms values. Fixes #705
> support longer ms values in ms2tick

- libraries/SPI/SPI.cpp
Fixes an issue identified here https://forums.adafruit.com/viewtopic.php?f=65&t=185669 where blitFrameBuffer hangs on Adafruit CLUE
> fix issue with blitFrameBuffer not working on Adafruit CLUE (HT @jimsbugs)

- libraries/SPI/SPI.cpp
- platform.txt
Fix dangerous issue where the function declared with return value does not return at all. Which could cause mis-matched issue on the execution stack. Force this as an error for all compiler warning option. See also https://forums.adafruit.com/viewtopic.php?f=62&t=186839
> add -Werror=return-type for all warning options

- libraries/Bluefruit52Lib/examples/Central/central_bleuart/central_bleuart.ino
Found a small spelling mistake in the sketch while having a read through. Couldn't help but update it.
> Fixed small spelling mistake in central_bleuart.ino sketch

- README.md
Looks like they changed their web structure.
http://www.silabs.com/products/mcu/pages/usbtouartbridgevcpdrivers.aspx is now 404
> Update silabs driver URL (was 404)

- .gitignore
- libraries/Bluefruit52Lib/src/bluefruit.h
- libraries/Bluefruit52Lib/src/clients/BLEClientIas.cpp
- libraries/Bluefruit52Lib/src/clients/BLEClientIas.h
- libraries/Bluefruit52Lib/src/services/BLEIas.cpp
- libraries/Bluefruit52Lib/src/services/BLEIas.h
This PR modifies `bluefruit.h` and adds files to support instantiation and detection of the Immediate Alert service, or IAS. This service only has one characteristic - the 'alert level'.
> Add support for Immediate Alert Service

- libraries/Bluefruit52Lib/examples/Central/central_hid/central_hid.ino
- libraries/Bluefruit52Lib/src/BLEDiscovery.cpp
- libraries/Bluefruit52Lib/src/BLEDiscovery.h
- libraries/Bluefruit52Lib/src/clients/BLEClientHidAdafruit.cpp
- libraries/Bluefruit52Lib/src/clients/BLEClientHidAdafruit.h
Hello! I have been working on a personal project recently and came across some missing functionality inside of the library. There was no way to connect as a Central role to an HID Gamepad peripheral. I went ahead and implemented it myself closely mirroring the Keyboard support.
This work is related to and extends upon the following old issues and pull requests.
- https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/228
- https://github.com/adafruit/Adafruit_nRF52_Arduino/pull/622
- https://github.com/adafruit/Adafruit_nRF52_Arduino/pull/688
The testing process I took is as follows:
1. Upload the (newly updated) example at `examples/Central/central_hid/central_hid.ino` to an Adafruit Feather NRF52840 Express board
2. Upload the example at …
> HID Gamepad Client & Central HID Gamepad example

- boards.txt
- platform.txt
- scripts/jlink/debug_custom.json
- scripts/openocd/daplink_nrf52.cfg
- scripts/openocd/jlink_nrf52.cfg
- tools/makeboards.py
- add support for IDE v2 debug with openocd + cmsis-dap probe such as pi debug probe.
- jlink over openocd cfg is also added for reference. However due to IDEv2 issue that only pick up default build.openocdscript (and ignore menu selection value). User with jlink want to debug can either use debug_custom.json or change the to jlink_nrf52.cfg instead
Ref: similar to https://github.com/adafruit/ArduinoCore-samd/pull/346
> Ide2 debug

- programmers.txt
ref https://forums.adafruit.com/viewtopic.php?t=202304
> fix space in path issue when burning bootloader with IDE v2

- cores/nRF5/HardwarePWM.cpp
- cores/nRF5/HardwarePWM.h
These functions allow for full control of the PWM configuration when direct register access is required and supplies a necessary function to reset the HwPWM to its default configuration.
A typical workflow might be:
1.  ```takeOwnership``` of an available HwPWM instance through the standard API
2. lookup the ```baseAddr``` of that HwPWM instance if direct configuration using NRF_PWMx is required
3. configure the HwPWM
4. ```addPin```(s) as necessary to the HwPWM
5. ```enable``` the HwPWM
6. ```stop``` the HwPWM when finished
7. ```removeAllPins``` from the HwPWM
8. ```releaseOwnership``` and return the HwPWM instance back to the available pool
> Add helper functions to HwPWM Instance

- libraries/Bluefruit52Lib/src/BLEAdvertising.cpp
Otherwise the data field gets corrupted (?) causing error msg "bool BLEAdvertising::_start(uint16_t, uint16_t): 364: verify failed, error = NRF_ERROR_INVALID_LENGTH" as mentioned in this comment: https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/197#issuecomment-1403674667
This apparently does not cause any issue when advertising the first time but when calling BLEAdvertising#clearData(), e.g. for changing the advertised bluetooth device name "on the fly", then starting the new advertisement procedure will fail.
see also https://devzone.nordicsemi.com/f/nordic-q-a/52573/sd_ble_gap_adv_set_configure-returns-error-nrf_error_invalid_length
> FIX #197 : Replace varclr with arrclr for BLEAdvertising _data fields

- libraries/RotaryEncoder/SwRotaryEncoder.cpp
I'm working on a project that has 3 rotary encoders. When I used this libary, I couldn't get the 3 switches to properly increment / decrement the steps when I called readAbs(). Looking back at the code, I see there was a change in 351cd82 which seemed to have caused the issue.
If I look previous to 351cd82, the _irq_handler was using digitalRead. I think switching to bitRead caused a mix up between the physical pin number vs. the port pin? I'm not entirely sure. I reimplemented the pre 351cd82 code and used the new ada_callback. Seems to be working great now!
> Fix _irq_handler

- libraries/Bluefruit52Lib/examples/Peripheral/beacon/beacon.ino
> add more description to beacon example, use non-connectable scannable undirected type

- cores/nRF5/HardwareSerial.h
- cores/nRF5/RingBuffer.cpp
- cores/nRF5/RingBuffer.h
- cores/nRF5/Uart.cpp
- cores/nRF5/Uart.h
add availableForWrite() for uart. Since UART does not use ring buffer for TX, therefore it is either busy or not. Fix #750
> add availableForWrite() for uart

- cores/nRF5/freertos/Source/include/portable.h
- cores/nRF5/freertos/Source/portable/MemMang/heap_3.c
- platform.txt
Hello everybody.
I have noticed that your FreeRTOS implementation only provides the threadsafe version of `malloc` and `free` while `realloc` and `calloc` are still not threadsafe. In case of very intense use of objects like `String` (which uses `realloc`) or in general of `realloc`/`calloc`, I noticed some hangs that I solved by implementing `pvPortRealloc` and `pvPortCalloc` and then wrapping the real `realloc` and `calloc` from the linker.
Hope it can help!
> Implemented thread-safe realloc and calloc

- libraries/Adafruit_LittleFS/src/Adafruit_LittleFS_File.cpp
Fixes leak of memory caused by failure to free file and directory structures when open fails.
> Fix memory leak on failure to open

- cores/nRF5/new.cpp
Added `__attribute__((weak))` weak linking annotation to new and delete operator overrides to allow for user-defined overrides.
> Making new/delete operators overridable

- cores/nRF5/wiring_analog.h
- cores/nRF5/wiring_analog_nRF52.c
Allow reading the VDDHDIV5 ADC source on devices that support it, such as nRF52840. For designs where the VDDH pin is connected to a battery, this is a great way to measure battery voltage without any additional external components.
> Add support for VDDHDIV5

- libraries/Bluefruit52Lib/src/BLEAdvertising.cpp
- libraries/Bluefruit52Lib/src/BLEAdvertising.h
bug is reported and discussed by forum user: https://forums.adafruit.com/viewtopic.php?t=216936
- fix(advertising): dynamic data not update
- fix typo
> fix(advertising): dynamic data not update

- .github/ISSUE_TEMPLATE/bug_report.yml
As I was about to file a bug, I noticed a typo, so figured it was worth sending a quick PR.
> Fix a copy-paste error in the bug report template.
